name: strydeenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - numpy>=1.15.0
  - scipy>=1.4.0
  - matplotlib
  - ipython
  - jupyter
  - pylops
  - tqdm
  - astropy
  - pip:
    - setuptools_scm
    - segyio
